### ISSUE TITLE
Add encrypted env vars to travis

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/legacy-client-java#1]
As this is a new repository it requires to add env vars from https://travis-ci.org/jaegertracing/jaeger-client-java/settings

**Comment by pavolloffay** [comment]
@jpkrohling IIRC you have configured these secrets, could you please add it to this repository too?

**Comment by pavolloffay** [comment]
codecov has been enabled but the token has to be probably added to travis

**Comment by pavolloffay** [comment]
It seems that codecov works without adding a token https://github.com/jaegertracing/legacy-client-java/pull/3#issuecomment-379820094

**Comment by jpkrohling** [comment]
`SIGNING_KEY_ID` and `SIGNING_KEY_PASSPHRASE` added to `jaegertracing/legacy-client-java`. I'm closing this issue as I think those are the only ones needed.

**Comment by pavolloffay** [comment]
@jpkrohling thanks

**Comment by pavolloffay** [comment]
@jpkrohling `travis.yml` also contains - `./travis/prepare-signing.sh $encrypted_677f232983c0_key $encrypted_677f232983c0_iv` in `before_install`

the jaeger-client-java defines these vars. Shouldn't be also added here?

**Comment by jpkrohling** [comment]
No, those are created automatically by Travis. I *think* those are created when you use the `travis encrypt` command for the first time.

**Comment by pavolloffay** [comment]
ok thanks, I think the last comment shouldn't be envrypted env in `travis.yml` re-encrypted? https://github.com/jaegertracing/legacy-client-java/blob/master/.travis.yml#L19

**Comment by jpkrohling** [comment]
That can be done via `travis encrypt`. If you add `--save` (or something like that), it will change the `.travis.yml` with the encrypted value.

**Comment by pavolloffay** [comment]
That is clear to me. 

The question is if those values should be re-encrypted

**Comment by jpkrohling** [comment]
Of course. The keys are tied to specific repositories. A value encrypted with the key for `jaeger-client-java` can't be decrypted by a key from `legacy-client-java`.

**Comment by pavolloffay** [comment]
Then I will reopen this as the encrypted values should be also added there. Do you want to submit a PR?
