### ISSUE TITLE
Release 0.27.0

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/legacy-client-java#8]
The new release (with deprecated tracer) should be cut to rather sooner to stop using `com.uber.jaeger`

@yurishkuro do you want to wait until you try the wrapper approach?

**Comment by pavolloffay** [comment]
Also note that `io.jaegertracing` will be released with `0.27.0-RC1` (initially) which will be the same version as used here.

**Comment by yurishkuro** [comment]
No, it's fine to cut a new release with deprecation. My only wish is that the deprecation messages should point to some document that explains why the classes are deprecated and what the migration strategy is. I.e. we could create an issue in this repo and use it as a documentation page.

**Comment by yurishkuro** [comment]
Release was done, waiting to appear in Central

**Comment by yurishkuro** [comment]
https://repo.maven.apache.org/maven2/com/uber/jaeger/jaeger-core/0.27.0/
